---
indexes:
    category: "categories"
    kategoria: "kategoriak"
    topic: "topics"
    section: "sections"
    lang: "langs"
taxonomies:
    category: "categories"
    kategoria: "kategoriak"
baseurl: ""
hu: "http://localhost:1313/hu/"
title: "devmonk"
...
